version: '3.0'
services:
  app:
    container_name: blog-app
    image: blog-app
    build: ./
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - blogdb
      - blogredis
  blogdb:
    image: postgres
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment:
      - POSTGRES_PASSWORD=$DB_PASS
      - POSTGRES_USER=$DB_USERNAME
      - POSTGRES_DB=blogappdb
  blogredis:
    image: redis/redis-stack-server
    ports:
        - "6379:6379"