spring:

  mail:
    host: smtp.mail.ru
    port: 465
    username: krekerok.blog_app@mail.ru
    password: ${EMAIL_PASS}
    protocol: smtps
    properties:
      mail:
        smtp:
          auth: true

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml

  config:
    import: optional:file:.env[.properties]

  datasource:
    url: jdbc:postgresql://${DB_HOST}/blogappdb
    username: ${DB_USERNAME}
    password: ${DB_PASS}

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: validate

  redis:
    database: 0
    host: ${REDIS_HOST}
    port: 6379
    timeout: 60000


app:
  jwtSecret: ${APP_JWT_SECRET}
  jwtExpirationMs: 86400000